### PR TITLE
upgrade cert-manager to 1.1.0

### PR DESCRIPTION
**Pull request by captncraig**
All I did was:

- delete charts/cert-manager
- update chartfile
- `tk tool charts vendor`

### CODE REVIEW

**Comment by Duologic** [comment]
As discussed directly, we need to consult the cert-manager changelog before upgrading, it might not be as smooth as this looks.

**Comment by captncraig** [comment]
That leaves an interesting problem for this library. If we merge these changes as in, then do manual steps to upgrade, we could cause problems for any (I doubt it tbh) other users of this lib. 

I am testing with this commit directly in one dev environment for now.

**Comment by Duologic** [comment]
The lack of a frictionless upgrade path is not caused by this Jsonnet library, rather the upstream Helm Chart.

**Review by Duologic — APPROVED** [review]

**Comment by captncraig** [comment]
Upgrade experience from dev-us-central1:

All deployments come up just fine. No hanging pods or anything like that. Some components failed because of missing CRDs, so I turned off custom_crds, and the chart made a thousand updates, then everything worked.

**Comment by captncraig** [comment]
But there isn't extensive usage there, so we will need to watch carefully when we roll to production clusters.

**Pull request merged**
