### PR TITLE
Add a dedicated scrape config for kube-dns

### PR DESCRIPTION
**Pull request by beorn7**

### CODE REVIEW

**Review by malcolmholmes — APPROVED** [review]

**Comment by beorn7** [comment]
Thanks @malcolmholmes . Lint problem should be fixed now.

I'll still wait for @DanCech and/or @jimnagy and will anyway only act on this next week.

Happy weekend everyone!

**Review by DanCech — APPROVED** [review]
Looks great!

**Comment by beorn7** [comment]
@captncraig I'm merging this now and will roll it out carefully. Pinging you here just in case it triggers anything unusual.

**Comment by beorn7** [comment]
I mean, rolling it out requires a vendoring update. I'll send a separate PR for that to @captncraig .

**Comment by beorn7** [comment]
AFAICS this will only do anything on GKE clusters (not AKS, for example). But I guess that's OK for now.

**Pull request merged**
