### PR TITLE
drop pods during scrapes in phase Failed or Succeeded

### PR DESCRIPTION
**Pull request by jtlisi**
Signed-off-by: Jacob Lisi <jacob.t.lisi@gmail.com>

### CODE REVIEW

**Comment by gouthamve** [comment]
Won't work right now. This needs to be in prometheus release, so it'll take 6-ish weeks :/

**Comment by jtlisi** [comment]
@tomwilkie https://github.com/prometheus/prometheus/pull/4824

**Comment by jtlisi** [comment]
@gouthamve @tomwilkie 
Now that prometheus 2.6.0-rc.0 is out can this be merged. I deployed it and it's working. It also will not break anything currently running.

**Comment by tomwilkie** [comment]
Merge away!

**Pull request merged**
