### PR TITLE
Add the polystat panel to grafana instances

### PR DESCRIPTION
**Pull request by tomwilkie**
Want to use this in the node-mixin.

Signed-off-by: Tom Wilkie <tom.wilkie@gmail.com>

### CODE REVIEW

**Comment by malcolmholmes** [comment]
This is tough. Would rather not add it to prometheus-ksonnet itself, just to support a single mixin.

It seems like this is a valid extension to the mixin model: add `grafana-plugins` to the supported options, then can add this directly to the `node-mixin`. Would want to support the new plugin provisioning method too. Does that work?

**Comment by tomwilkie** [comment]
Yeah, I think I can make that work.

**Comment by malcolmholmes** [comment]
https://grafana.com/docs/grafana/latest/administration/provisioning/#plugins for the new way of provisioning that we should ideally support.

**Comment by robx** [comment]
> https://grafana.com/docs/grafana/latest/administration/provisioning/#plugins for the new way of provisioning that we should ideally support.

Note that plugin provisioning is only necessary for app plugins; datasource and panel plugins only need to be installed. So adding support for plugin provisioning shouldn't be necessary here.

(I agree that it would be good to support though. An example of doing it explicitly is the [alerting UI on dev-us-central1](https://github.com/grafana/deployment_tools/blob/00569f2cf9633cf4bbc1bb8915fb3805c00cef99/ksonnet/environments/default/dev-us-central1.default/main.jsonnet#L126).)

**Comment by tomwilkie** [comment]
Yes, thank you Rob - this is intended for panel plugins right now.

@malcolmholmes this seems to work in my testing, ready for another look if you don't mind?

**Review by malcolmholmes — APPROVED** [review]
Looks good to me.

**Pull request merged**
