### PR TITLE
ha-mixin: unroll per-replica ConfigMap generation.

### PR DESCRIPTION
**Pull request by falfaro**
This allows overriden a replica-specific parameter of any Prometheus.

### CODE REVIEW

**Review by Duologic — COMMENTED** [review]
I don't think this is needed, you can already access the individual keys in a configMap.

**Comment by grafanalf** [comment]
> I don't think this is needed, you can already access the individual keys in a configMap.

I honestly thing my approach is much cleaner than this and more readable. Given how complex our Jsonnet codebase is, the easier making overrides more readable and easy to use are, the better.

**Comment by falfaro** [comment]
> I don't think this is needed, you can already access the individual keys in a configMap.

I honestly thing my approach is much cleaner than this and more readable. Given how complex our Jsonnet codebase is, the easier making overrides more readable and easy to use are, the better.

**Comment by falfaro** [comment]
So, you don't agree this new code is more readable and easy to follow, and easier to debug (evaluate) than the old one?

**Review by Duologic — APPROVED** [review]

**Comment by Duologic** [comment]
The description didn't read like it was a readability improvement.

**Pull request merged**
