### PR TITLE
Kafka observ lib update: add kafka overview dashboard

### PR DESCRIPTION
**Pull request by v-zhuravlev**
**Added:**
1) Added **kafka cluster overview** dashboard with the following rows:
  - Overview
  - Throughput
  - Replication
  - Requests time breakdown
  - Message conversion
  - Zookeeper client
  - Process overview (from process-observ-lib)
  - JVM overview (from jvm-observ-lib)
  - JVM memory (from jvm-observ-lib)
  - JVM threads (from jvm-observ-lib)
Default view:
image

All rows expanded:
image

2) Updated **zookeeper overview** dashboard with the following rows (imported from zookeeper-observ-lib):
  - Zookeeper overview (with current roles timeline)
  - Latency
  - Process overview (from process-observ-lib)
  - JVM overview (from jvm-observ-lib)
  - JVM memory (from jvm-observ-lib)
  - JVM garbage collection (from jvm-observ-lib)
  - JVM threads (from jvm-observ-lib)
Default view:
image
Rows opened:
image

3) Added alerts for JVMs (for zookeeper and kafka)
4) Added kafka alerts

**Dropped:**
- overview dashboard from kafka-mixin (use overview dashboard from kafka-observ-lib instead)
- alerts from kafka-mixin ( use alerts from kafka-observ-lib instead)

**Dependencies used/updated:**
jvm-observ-lib (added jmx_exporter metricsSource, used for kafka JVM rows)
process-observ-lib (added jmx_exporter metricsSource, used for kafka process overview row)
zookeeper-observ-lib

### CODE REVIEW

**Comment by v-zhuravlev** [comment]
TIP: can check commit messages for more breakdown of changes: https://github.com/grafana/jsonnet-libs/pull/1298/commits

**Comment by v-zhuravlev** [comment]
Note: thanks to https://github.com/grafana/grafonnet/pull/214, rows can be defined in observability libraries in a way that one can decide rows should be collapsed/uncollapsed by just setting `row.withCollapsed(false)` or `row.withCollapsed(true)`.

**Comment by gaantunes** [comment]
Can you add a sceeenshot of the topics and consumer group dashboards? I am curious what is the implication of making their names the instance label selector.

**Comment by v-zhuravlev** [comment]
It was added before , You can find topic dashboard  screenshot in the
readme file

Пн, 12 авг. 2024 г. в 19:52, gaantunes ***@***.***>:

**Comment by v-zhuravlev** [comment]
https://github.com/grafana/jsonnet-libs/blob/vzhuralev/co-kafka/kafka-observ-lib/README.md

**Comment by v-zhuravlev** [comment]
> Can you add a sceeenshot of the topics and consumer group dashboards? I am curious what is the implication of making their names the instance label selector.

I left a comment about it: " // this.instanceLabels is omitted, as it would point to kafka_exporter instance."  so instance label doesn't show anything useful, just kafka_exporter instance label on the topics dashboard, so can be omitted.

**Comment by gaantunes** [comment]
> > Can you add a sceeenshot of the topics and consumer group dashboards? I am curious what is the implication of making their names the instance label selector.
> 
> I left a comment about it: " // this.instanceLabels is omitted, as it would point to kafka_exporter instance." so instance label doesn't show anything useful, just kafka_exporter instance label on the topics dashboard, so can be omitted.

Got it, thank you!

**Review by gaantunes — APPROVED** [review]
:rocket:

**Pull request merged**
