### PR TITLE
Allow patching by name/kind after helm.template

### PR DESCRIPTION
**Pull request by malcolmholmes**
Currently, `patchKubernetesObjects` patches *all* objects. I want to add a node-selector to all StatefulSets. This PR adds an optional `kind` and `name` elements which allow us to patch specific resources rather than all of them.

### CODE REVIEW

**Review by sh0rez — CHANGES_REQUESTED** [review]
I feel like this is slowly creeping the scope of the package.

imo helm-util is supposed to provide helm rendering support, and not much beyond that.

While the code for object mutation, including tree traversal is cool, this really should be a package in its own right, or part of kausal or k8s-util

**Comment by malcolmholmes** [comment]
that's fair enough. Could be a dependency of helm-util too. `object-util` for example.

**Comment by Duologic** [comment]
I think we can add this here for now, but yes, ideally this moves out of helm-util, sounds like it might belong in k8s-util once we get a move on that.

**Comment by Duologic** [comment]
@malcolmholmes Is this going anywhere?

**Comment by malcolmholmes** [comment]
Yes, I for one need it. I totally agree that there's a heap of useful functionality (e.g. deep patching functions, generic functions to patch objects in lists, etc) that would make sense inside a more generic `object-utils` or `tanka-utils`. But that's all for the future.

**Comment by malcolmholmes** [comment]
i.e. can we approve/merge this?

**Review by Duologic — APPROVED** [review]
Agreed, let's merge this with the prospect of a more generalized library.

**Review by sh0rez — APPROVED** [review]

**Pull request merged**
