### PR TITLE
Add `k.util.secretVolumeMountAnnotated`

### PR DESCRIPTION
**Pull request by colega**
We have configMapVolumeMount that adds config map annotations to the
deployments to ensure that pods are restarted when the contents of the
config map changes. Why not having the same for secrets?

Signed-off-by: Oleg Zaytsev <mail@olegzaytsev.com>

### CODE REVIEW

**Comment by colega** [comment]
@Duologic asking you for a review as Github suggested that :)

**Comment by Duologic** [comment]
I have been trying to upstream these into the k8s-libsonnet library, would you be interested in contributing it here: https://github.com/jsonnet-libs/k8s/blob/master/libs/k8s/custom/core/volumeMounts.libsonnet#L123 ?

**Comment by Duologic** [comment]
@colega I'm porting it into k8s-libsonnet here: https://github.com/jsonnet-libs/k8s/pull/181

**Comment by colega** [comment]
Thanks, I haven't had time to work on this. I guess we can close this PR now.

**Pull request closed without merging**
