### PR TITLE
Enable histograms for http requests and db queries

### PR DESCRIPTION
**Pull request by bergquist**
Signed-off-by: bergquist <carl.bergquist@gmail.com>

### CODE REVIEW

**Comment by malcolmholmes** [comment]
Note that prom-ksonnet now builds upon a separate Grafana lib. Should this be set for prometheus-ksonnet users, or every jsonnet Grafana user?

**Comment by bergquist** [comment]
Moved it to the grafana lib instead :)

**Comment by bergquist** [comment]
ping @malcolmholmes

**Review by malcolmholmes — APPROVED** [review]

**Comment by bergquist** [comment]
:D

**Pull request merged**
