### PR TITLE
Wildfly `k8s` plugin support

### PR DESCRIPTION
**Pull request by algchoo**
### Description

This PR updates the Wildfly mixin to support the `grafana-k8s-plugin`

### Changes
* [added enableMultiCluster and selectors](https://github.com/grafana/jsonnet-libs/commit/dc431cd9fd2c7b737be5c4a990cc386fe14a4f33)
* [updated dashboards to use selectors for k8s support](https://github.com/grafana/jsonnet-libs/commit/893841c8253534647aac7159532db83f29a8738e)
* [updated log panel query to allow various file paths](https://github.com/grafana/jsonnet-libs/commit/1739ee9c9119b9e0d138eef3d9a950e78d1edddc)
* [fixed typo](https://github.com/grafana/jsonnet-libs/commit/b26b5fb221dc15dc4806cabdb7a9520c30d11dae)

### CODE REVIEW

**Review by JonathanWamsley — APPROVED** [review]
LGTM 👍

**Review by Caleb-Hurshman — APPROVED** [review]
Nice work ✅

**Review by Dasomeone — APPROVED** [review]
LGTM

**Review by gaantunes — APPROVED** [review]
LGTM

**Pull request merged**
