### PR TITLE
Make grafana a library in its own right

### PR DESCRIPTION
**Pull request by malcolmholmes**
This has to be the simplest ever PR. Given that `prometheus-ksonnet` imports `grafana/grafana.libsonnet`, moving it from inside the `prometheus-ksonnet` directory to `vendor/grafana` works just the same.

Moving this code outside of its parent has the benefit of allowing us to offer a generic "mixin-aware" Grafana library, independent of Prometheus, whilst continuing to support the `prometheus-ksonnet` use-case as before.

N.B. The vendoring is not tested yet, as it requires it to be merged first. We could either do that in quick succession, or do this in two PRs (copy/delete instead of move).

### CODE REVIEW

**Review by sh0rez — APPROVED** [review]
LGTM.

You can test vendoring by locally changing the version to this branch and running install. If that works, it's good to go

**Review by jdbaldry — APPROVED** [review]
LGTM

**Review by tomwilkie — APPROVED** [review]

**Comment by malcolmholmes** [comment]
Finally got around to confirming this branch as @sh0rez suggested (after much needed rebasing). Worked fine.

**Review by tomwilkie — APPROVED** [review]

**Comment by malcolmholmes** [comment]
Superceded by #449 which does the separation in a much more intelligent way.

**Pull request closed without merging**
