### PR TITLE
Add memcached ksonnet

### PR DESCRIPTION
**Pull request by gouthamve**
Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>

### CODE REVIEW

**Comment by tomwilkie** [comment]
I think you're missing a jsonnet-bundler file specifying the dependency on the jsonnet-utils lib?

**Comment by tomwilkie** [comment]
Like this: https://github.com/grafana/jsonnet-libs/blob/master/prometheus-ksonnet/jsonnetfile.json#L43

**Comment by tomwilkie** [comment]
LGTM otherwise.

**Comment by gouthamve** [comment]
Huh, yes. That was missing for consul as well. Added it.

**Pull request merged**
