### PR TITLE
fix(ksonnet-util): prune instead of hide

### PR DESCRIPTION
**Pull request by Duologic**
Hiding is also affected volumeClaimTemplates that are added in a later mixin.

### CODE REVIEW

**Comment by malcolmholmes** [comment]
How does this pruning work? Don't we still end up with {}? Or if not, doesn't the empty element get pruned away so removing nothing?

**Comment by Duologic** [comment]
If therer are no claims, then we can safely assume `volumeClaimTemplates` equals `{}`. So, then what `std.prune()` does is remove 'keys' that are in fact a null value like [], {} and null, or that at least that is how I understand it.

From the docs:
> Recursively remove all "empty" members of a. "Empty" is defined as zero length `arrays`, zero length `objects`, or `null` values. The argument a may have any type.

The hardest part for me to understand is to know when `std.prune()` is applied, but it looks like this happens after the jsonnet tree has formed, how else could it do it recursively?

Side node: the 'recursively' is also treacherous, I learned it the hard way a while back while using it on a whole tree, it messed up the cert-manager CRDs that expected an empty array somewhere.

**Comment by malcolmholmes** [comment]
I don't think this will work.
```
{
  spec: {
    volumeClaimTemplates: {},
  },
} + {
  spec+: std.prune({ volumeClaimTemplates: {} }),
}
```
In this scenario, we are adding `{}` to the spec, the prune will always reduce to just `{}` which is a no-op.

Can we come up with some test cases that prove the code here works as expected?

**Comment by Duologic** [comment]
I'm not doing that, am I? This only happens inside the new() function, it you doing something else outside that function, then that is not going to solve that.

**Comment by Duologic** [comment]
Covered for in #426

**Pull request closed without merging**
