### PR TITLE
Fix daemonset does not generate manifest

### PR DESCRIPTION
**Pull request by c0ffeec0der**
Fix issue https://github.com/grafana/jsonnet-libs/issues/433

### CODE REVIEW

**Comment by c0ffeec0der** [comment]
I am not sure why linting fail.. It works when I run loki with tanka. Please take a look at this as it is breaking loki tanka installation

**Comment by c0ffeec0der** [comment]
Hello anyone looking at this? This PR will fix issue the lib implementation in loki. Thank you

**Comment by c0ffeec0der** [comment]
@Duologic would you be able to review this? It's breaking the lib implementaion in loki. I use this code and it works. I checked the linting error and it doesn't tell much why it is error. It shouldn't be error because it works when I run with loki

**Comment by Duologic** [comment]
Can you make a minimal reproducible example that fails before and succeeds after this fix?

**Comment by c0ffeec0der** [comment]
Before code change,

1. Install loki with https://grafana.com/docs/loki/latest/installation/tanka/#install-loki-with-tanka
2. Error occurs (https://github.com/grafana/loki/issues/3192)
```
evaluating jsonnet: RUNTIME ERROR: function expected 1 positional argument(s), but got 2
        C:\main\repos\1-infra\2-services\3-monitoring\vendor/ksonnet-util/grafana.libsonnet:27:9-50     function <anonymous>    
        C:\main\repos\1-infra\2-services\3-monitoring\vendor/promtail/promtail.libsonnet:67:5-71        object <anonymous>      
        During manifestation
```
3. After code change, the error is gone

It seems this line 
` super.new(name, containers, podLabels={}) +`

is referring to the generated library instead of the old ksonnet util lib. CMIIW

**Comment by Duologic** [comment]
Your example contains many elements that make it hard to determine the cause. A minimal reproducible example should help us get to the root of the problem.

**Comment by Duologic** [comment]
The Loki library has locked the ksonnet-util version: https://github.com/grafana/loki/blob/b29bc19/production/ksonnet/loki/jsonnetfile.lock.json#L24-L33

I just did a quick run with this version and also get an error, imo the Loki library should not lock versions like that.

**Comment by c0ffeec0der** [comment]
CMIIW the lock file exist for any library used in jsonnetfile.json. It is the concept for using jb (jsonnet bundler)

To see the version used, refer to jsonnetfile.json

https://github.com/grafana/loki/blob/b29bc19d7cf20285231a98ae0ec15b1421e7daa6/production/ksonnet/loki/jsonnetfile.json#L22-L30

Loki is using ksonnet-lib master version

**Comment by Duologic** [comment]
I cannot reproduce with above instructions.

I've tested this with this setup: https://github.com/Duologic/temp-debug-ksonnet-util/tree/1ebd3166c2b4d12e7da0c8f8d7b5a014eab54acb

Please have a look at your project jsonnetfile.lock.json to ensure it matches jsonnet-libs master.

**Comment by snoord** [comment]
To preface this comment, I have only started using Jsonnet in the last day, so I apologise if this comment is incorrect or irrelevant.

That said, I was having the same issue as @c0ffeec0der - I have been trying to generate this DaemonSet manifest using the Tanka command `tk show environments/default`:
```jsonnet
// environments/default/main.jsonnet
(import 'github.com/grafana/jsonnet-libs/ksonnet-util/kausal.libsonnet') +
{
  _config:: {
    example: {
      name: 'example',
      image: 'example/image:latest',
    },
  },

  local c = $._config,
  local container = $.core.v1.container,
  local daemonSet = $.apps.v1.daemonSet,
  local port = $.core.v1.containerPort,

  manifest: {
    daemonSet: daemonSet.new(c.example.name, containers=[
      container.new(c.example.name, c.example.image)
      + container.withPorts(
        port.newNamed(12345, 'example')
      ),
    ]),
  },
}
```

Using this manifest would result in the following error:
```
Error: evaluating jsonnet: RUNTIME ERROR: function expected 1 positional argument(s), but got 2
        /Users/samuel/code/jsonnet-example/vendor/github.com/grafana/jsonnet-libs/ksonnet-util/grafana.libsonnet:27:9-50        function <anonymous>
        /Users/samuel/code/jsonnet-example/environments/default/main.jsonnet:(17:16)-(22:7)     object <anonymous>
        During manifestation
```

I then tried using the modified code from @c0ffeec0der, which resulted in the successful generation of the DaemonSet manifest.

However, I remembered that my `lib/k.libsonnet` file had an additional import line that I added when I started trying to learn Tanka + Jsonnet:
```jsonnet
// lib/k.libsonnet
(import 'github.com/jsonnet-libs/k8s-alpha/1.18/main.libsonnet') +
(import 'github.com/jsonnet-libs/k8s-alpha/1.18/extensions/kausal-shim.libsonnet')
```

I removed @c0ffeec0der's  changes to `ksonnet-util/grafana.libsonnet` and the `kasual-shim.libsonnet` line from `lib/k.libsonnet`:
```diff
// lib/k.libsonnet
+ (import 'github.com/jsonnet-libs/k8s-alpha/1.18/main.libsonnet')
- (import 'github.com/jsonnet-libs/k8s-alpha/1.18/main.libsonnet') +
- (import 'github.com/jsonnet-libs/k8s-alpha/1.18/extensions/kausal-shim.libsonnet')
```

...and I could successfully generate the DaemonSet manifest!

```bash
❯ tk show environments/default
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: example
  namespace: default
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      name: example
  template:
    metadata:
      labels:
        name: example
    spec:
      containers:
      - image: example/image:latest
        imagePullPolicy: IfNotPresent
        name: example
        ports:
        - containerPort: 12345
          name: example
      tolerations:
      - effect: NoSchedule
        operator: Exists
  updateStrategy:
    type: RollingUpdate
```

Not really sure how or why this worked (as I said, I'm only at the beginning of my journey into Jsonnet), but I thought this might be useful to others who know a bit more than I do 🙂

**Comment by Duologic** [comment]
Aha, that seems to be it, the kausal-shim is now integrated into ksonnet-util. Removing that is the right choice.

It looks like the docs have recently (8 days ago) been updated, it doesn't reference the kausal-shim anymore.

@c0ffeec0der Can you confirm?

@snoord Thank your for that insight.

**Comment by Duologic** [comment]
I'm considering this solved.

**Comment by c0ffeec0der** [comment]
@Duologic Apologies, I was concentrating on other stuff and went deep. Just taking a look at this one. Confirm this is solved

@snoord Thank you so much!

**Pull request closed without merging**
