### PR TITLE
feat(tanka-util): add withApplyStrategy

### PR DESCRIPTION
**Pull request by partcyborg**
Add helper function `withApplyStrategy` to tanka-util

### CODE REVIEW

**Comment by partcyborg** [comment]
It appears the CLA check isn't working as I have signed the CLA twice now and it still shows up as pending.

**Comment by nikosmeds** [comment]
There have been a few similar reports of CLA issues. I tried the "recheck" option but it still hasn't resolved. Can you try closing and re-opening the PR?

**Comment by kminehart** [comment]
I just realized, @partcyborg , the CLA check checks the github users that submitted the commits and not the person who opened the PR. In this case, that'd be @mattwilder. Can we get @mattwilder to sign the CLA for these changes? :)

**Comment by mattwilder** [comment]
Ahh, that makes sense.  Signed from both accounts.

**Review by nikosmeds — APPROVED** [review]
Thanks everyone.

**Pull request merged**
