### PR TITLE
ceph-mixin rate standardization

### PR DESCRIPTION
**Pull request by gaantunes**
Update all queries to use $__rate_interval for rate, irate, and increase function calls.

### CODE REVIEW

**Review by rgeyer — APPROVED** [review]
LGTM.

The `$interval` is still used on the targets themselves, but not in the promql function calls. I *think* that's okay.

**Comment by gaantunes** [comment]
Do you think it would be better to set the interval to $__rate_interval as well? I didn`t change it on any of the other dashboards, wasn`t paying attention to this to be honest...

**Comment by rgeyer** [comment]
> Do you think it would be better to set the interval to $__rate_interval as well? I didn`t change it on any of the other dashboards, wasn`t paying attention to this to be honest...

Yeah, if it isn't being used explicitly, we can remove it.. I'll make another quick commit to handle that.

**Comment by rgeyer** [comment]
> > Do you think it would be better to set the interval to $__rate_interval as well? I didn`t change it on any of the other dashboards, wasn`t paying attention to this to be honest...
> 
> Yeah, if it isn't being used explicitly, we can remove it.. I'll make another quick commit to handle that.

Sorry, I just realized this was one you're working on. You're welcome to remove interval from the panels, and as a template var 😂

**Comment by gaantunes** [comment]
> > > Do you think it would be better to set the interval to $__rate_interval as well? I didn`t change it on any of the other dashboards, wasn`t paying attention to this to be honest...
> > 
> > 
> > Yeah, if it isn't being used explicitly, we can remove it.. I'll make another quick commit to handle that.
> 
> Sorry, I just realized this was one you're working on. You're welcome to remove interval from the panels, and as a template var 😂

Will do it :D

**Pull request merged**
