### PR TITLE
refactor(mysql_exporter): modular approach to passwords

### PR DESCRIPTION
**Pull request by Duologic**
This change is expected to be 100% backwards compatible. Most logic moved into functions in `main.libsonnet`. Notice the
use of the `withPassword` function in `mysql-exporter.libsonnet`.

I've included a few options we use downstream that will be available in mysqld_exporter v0.13.0, ~the rc already seems to support it~ v0.13.0 is now out, updated accordingly.

I've moved the new code into mysqld-exporter and added a deprecation notice to mysql-exporter, this should allow for a transition period.

### CODE REVIEW

**Comment by bergquist** [comment]
> I wonder whether we should take the opportunity to rename this lib to mysqld_exporter for more consistency across the board feedback appreciated.

Would it make sense to have two libs during a transition period?

**Comment by Duologic** [comment]
What would each encompass?

**Review by dafydd-t — APPROVED** [review]
Happy with the changes. Next time I make any jsonnet libs I'll attempt to take inspiration from this function-based approach.

Happy with the rename too. 

> What would each encompass?

The exact same thing, I imagine.

**Comment by Duologic** [comment]
Ah, yis, misunderstood the question, will do.

**Comment by Duologic** [comment]
> I've moved the new code into mysqld-exporter and added a deprecation notice to mysql-exporter, this should allow for a transition period.

**Pull request merged**
